### ISSUE TITLE
Handler invoked synchronously. Does not protect against reentrancy.

### ISSUE THREAD

**Issue by erights** [Agoric/eventual-send#19]
https://github.com/Agoric/eventual-send/blob/010efde2ee97f9aa59be43daebb5eadcace14f2b/src/index.js#L32

This is a bug. At https://github.com/tvcutsem/es-lab/blob/f1417a67741bb727b40f47e6c2b061e20a5d7098/src/ses/nanoq.js#L33 I see that the bug was in my original too. We need to fix this, even though it will disrupt the ordering again.

Thanks to @devsnek at https://github.com/Agoric/proposal-infix-bang/issues/5#issuecomment-511128751 for noticing this.

**Comment by erights** [comment]
The bug was not in the earlier original https://github.com/tvcutsem/es-lab/blob/f1417a67741bb727b40f47e6c2b061e20a5d7098/src/ses/makeQ.js#L611

**Comment by michaelfig** [comment]
I had this defence already before last night but undid it to get SwingSet tests to pass.  I will gladly undo my change and get back the half-async behaviour (so that fulfilledHandler is in a later turn), and then make it fully-async (so that unfulfilledHandler is in a later turn too).

**Comment by warner** [comment]
in case people run into this problem in the future: this bug was fixed in the code that went into the 0.1.10 release, but a problem during the release process meant that the tarball uploaded to NPM included stale `dist` bundles, which did not include the fix. So the first release that fixes this problem is 0.2.0.

**Comment by warner** [comment]
in the old repo. this was eventual-send issue 19
